# Generated by Django 5.2.5 on 2026-02-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_rename_appartment_number_address_apartment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowyourcustomer',
            name='document_file',
            field=models.FileField(blank=True, upload_to='kyc-document/'),
        ),
    ]
