# Generated by Django 5.2.5 on 2026-02-18 14:54

import django.core.validators
import zoolflow.customers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_alter_knowyourcustomer_document_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-main_address', '-updated_at']},
        ),
        migrations.AlterField(
            model_name='address',
            name='apartment_number',
            field=models.CharField(blank=True, default='N', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='building_number',
            field=models.CharField(blank=True, default='N', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, default='N', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='line',
            field=models.CharField(blank=True, default='N', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='main_address',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, default='N', max_length=10, validators=[django.core.validators.RegexValidator(message='In Egypt must be five digits.', regex='^\\d{5}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, default='N', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, default='N', help_text='Name must match the name in the document to succeed validation', max_length=50, validators=[zoolflow.customers.validators.validate_first_name]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, default='N', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='knowyourcustomer',
            name='document_id',
            field=models.CharField(blank=True, default='N', max_length=100),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('main_address', True)), fields=('customer',), name='single_main_address_for_a_customer'),
        ),
    ]
