# Generated by Django 5.2.5 on 2026-02-19 08:05

import zoolflow.customers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_alter_address_options_alter_address_apartment_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, help_text='Name must match the name in the document to succeed validation', max_length=50, null=True, validators=[zoolflow.customers.validators.validate_first_name]),
        ),
        migrations.AlterConstraint(
            model_name='address',
            name='single_main_address_for_a_customer',
            constraint=models.UniqueConstraint(condition=models.Q(('main_address', True)), fields=('customer',), name='single_main_address_for_a_customer', violation_error_message='only one main address can be'),
        ),
    ]
