# Generated by Django 5.2.5 on 2026-03-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_alter_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="main_address",
            field=models.BooleanField(default=False),
        ),
    ]
