# Generated by Django 5.2.5 on 2026-03-11 18:36

import zoolflow.customers.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0012_alter_address_main_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowyourcustomer",
            name="document_file",
            field=models.FileField(
                blank=True,
                storage=zoolflow.customers.models.get_kyc_storage,
                upload_to="kyc/",
            ),
        ),
    ]
