# Generated by Django 5.2.5 on 2026-02-09 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_emailcode_verificationcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verificationcode',
            options={'ordering': ['-created_at']},
        ),
    ]
