# Generated by Django 5.2.5 on 2026-02-09 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_verificationcode_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verificationcode',
            old_name='expiry_time',
            new_name='expire_at',
        ),
    ]
