# Generated by Django 5.2.5 on 2026-02-11 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_expiry_time_verificationcode_expire_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerificationCode',
        ),
    ]
