# Generated by Django 5.2.5 on 2026-02-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_rename_key_emailevent_idempotent_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailevent',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('queued', 'Queued'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='initiated', max_length=20),
        ),
    ]
