# Generated by Django 5.2.5 on 2026-03-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0006_alter_emailevent_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailevent",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("transaction_update", "Transaction Update"),
                    ("verification_code", "Verification Code"),
                ],
                max_length=100,
            ),
        ),
    ]
