# Generated by Django 5.2.5 on 2026-02-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_rename_paymob_order_id_transaction_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('error', 'Error'), ('voided', 'Voided'), ('authorized', 'Authorized')], default='initiated', editable=False, max_length=20),
        ),
    ]
