# Generated by Django 5.2.5 on 2026-03-11 18:30

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0007_alter_transaction_order_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                condition=Q(idempotency_key__isnull=False),
                fields=("customer", "idempotency_key"),
                name="uniq_customer_idempotency_key",
            ),
        ),
    ]
